#!/bin/bash

set -eu -o pipefail

LIBNAME=Adafruit_TFTLCD_Library

TEMPDIR=$(mktemp -d)
mkdir ${TEMPDIR}/${LIBNAME}
cp -r examples *.cpp *.h ${TEMPDIR}/${LIBNAME}/
pushd ${TEMPDIR}
zip ${LIBNAME}.zip ${LIBNAME}/*
popd
mv ${TEMPDIR}/${LIBNAME}.zip ./
rm -r ${TEMPDIR}
